spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/film_arsivi
spring.datasource.username=postgres
spring.datasource.password=kendi_db_sifren
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

proje.gizli.anahtar=1234
